ss/retrieveUnpackaged/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schema_Name__c</fullName>
        <label>Schema Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>127</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_id__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>NVARCHAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLOAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/classes/FieldService.cls
public class FieldService {
    public static void setFieldId(List<Field__c> fields){
        Entity__c entityDb = [
            SELECT Name__c, Schema_Name__c, Table_Name__c, Id__c 
            FROM Entity__c 
            WHERE Id =: fields.get(0).Entity_id__c
        ];
        for(Field__c field: fields){
            field.Id__c = (entityDb.Id__c + + field.Column_Name__c).toUpperCase();
        }
    }
    
    public static void insertFieldIntoRemoteService(List<Field__c> fields){
        Entity__c entityDb = [
            SELECT Name__c, Schema_Name__c, Table_Name__c, Id__c, (SELECT Id__c, Name__c, Field_Type__c, Length__c, Column_Name__c, Entity_id__c FROM Fields__r)
            FROM Entity__c 
            WHERE Id =: fields.get(0).Entity_id__c
        ];
        EntityDto entity = new EntityDto(entityDb);
        String data = JSON.serialize(entity);
        HttpService.updateData(data);
    }
    
    public static void updateFieldIntoRemoteService(List<Field__c> fields){
        Entity__c entityDb = [
            SELECT Name__c, Schema_Name__c, Table_Name__c, Id__c, (SELECT Id__c, Name__c, Field_Type__c, Length__c, Column_Name__c, Entity_id__c FROM Fields__r)
            FROM Entity__c 
            WHERE Id =: fields.get(0).Entity_id__c];
        EntityDto entity = new EntityDto(entityDb);
        String id = entity.id;
        String data = JSON.serialize(entity);
        HttpService.patchData(id, data);
    }
    
    public static void deleteFieldIntoRemoteService(List<Field__c> fields){
        Entity__c entityDb = [
            SELECT Name__c, Schema_Name__c, Table_Name__c, Id__c, (SELECT Id__c, Name__c, Field_Type__c, Length__c, Column_Name__c, Entity_id__c FROM Fields__r)
            FROM Entity__c 
            WHERE Id =: fields.get(0).Entity_id__c
        ];
        EntityDto entity = new EntityDto(entityDb);
        String data = JSON.serialize(entity);
        HttpService.updateData(data);
    }
}