ss/retrieveUnpackaged/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schema_Name__c</fullName>
        <label>Schema Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>127</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Entity_id__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/classes/Entity.cls
public class Entity{
    public String id{get; set;}
    public String name{get; set;}
    public String schemaName{get; set;}
    public String tableName{get; set;}
    public List<Field> fieldList{get; set;}
    public Boolean fullUploadData{get; set;}
    
    public Entity(Entity__c entity){
        id = (entity.Schema_Name__c + entity.Table_Name__c).toUpperCase();
        name = entity.Name__c;
        schemaName = entity.Schema_Name__c;
        tableName = entity.Table_Name__c;
        fullUploadData = false;
        if(!entity.Fields__r.isempty()){
            fieldList = new List<Field>();
            for(Field__c field: entity.Fields__r){
               Field fieldDto = new Field(field);
               fieldList.add(fieldDto); 
            }
        }
    }
    public Entity(){
        
    }
    public void addFileds(List<Field__c> createdFieldList){
            fieldList = new List<Field>();
            for(Field__c field: createdFieldList){
               Field fieldDto = new Field(field);
               fieldList.add(fieldDto); 
        }
    }
    
    public Entity__c convertIntoSEntity(){
        Entity__c entity = new Entity__c();
        entity.Id__c = this.id;
        entity.Name__c = this.name;
        entity.Schema_Name__c = this.schemaName;
        entity.Table_Name__c = this.tableName;
        return entity;    
    }
    
    public list<Field__c> getListSFields(){
        List<Field__c> listFields = new List<Field__c>();
        for(Field field: this.fieldList){
            Field__c sfield = field.convertIntoSField();
            listFields.add(sfield);
        }
        return listFields;
    }
}