ss/retrieveUnpackaged/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schema_Name__c</fullName>
        <label>Schema Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>127</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Entity_id__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>NVARCHAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLOAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/objects/Taken_request__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request</label>
        <type>Checkbox</type>
    </fields>
    <label>Taken_request</label>
</CustomObject>

ui/src/classes/EditEntityController.cls
public class EditEntityController {

    public String entityId{get; set;}
    public Entity__c entity{get; set;}
    public List<Field__c> fields{get; set;}
    public String fieldId{get; set;}
    public Integer fakeId{get; set;}
    Entity customEntity{get; set;}
    public Boolean fullUploadData{get; set;}
    public String fileLoadType{get; set;}
    public SelectOption[] loadFileTypeOptions{get; set;}
    
    public EditEntityController(){
        entityId = apexpages.currentpage().getparameters().get('entityID');
        customEntity = HttpService.getEntity(entityId);
        entity = customEntity.convertIntoSEntity();
        fields = customEntity.getListSFields();
        fullUploadData = customEntity.fullUploadData;
        fakeId = 1;
        loadFileTypeOptions = new SelectOption[]{};
        loadFileTypeOptions.add(new SelectOption('false', 'Increase'));
        loadFileTypeOptions.add(new SelectOption('true', 'Full load'));
        fileLoadType = String.valueOf(customEntity.fullUploadData);
    }
    
    public void createField(){
        Field__c field = new Field__c(Entity_id__c = entity.Id, Id__c = String.valueOf(fakeId++), Field_Type__c = 'NVARCHAR');
        fields.add(field);
    }
    
    public void save(){
     
        try{
            customEntity.name = entity.Name__c;
            customEntity.schemaName = entity.Schema_Name__c;
            customEntity.tableName = entity.Table_Name__c;    
            customEntity.addFileds(fields);
            customEntity.fullUploadData = Boolean.valueOf(fileLoadType);
            String info = EntityService.checkCorrectDataUpdate(customEntity);
            if(!String.isEmpty(info)){
                throw new EntityExistedException(info);
            }
            String data = JSON.serialize(customEntity);
            HttpService.updateData(data);
        }catch(Exception ex){
             ApexPages.addMessages(ex);
        }
    }
    
    public void cancle(){
        customEntity = HttpService.getEntity(entityId);
        entity = customEntity.convertIntoSEntity();
        fields = customEntity.getListSFields();
    }
    
    public void deleteField(){
       List<Field__c> updateFields = customEntity.getListSFields(); 
       for(Integer i = 0; i < fields.size(); i++){
            if(fields.get(i).Id__c == fieldId){
              fields.remove(i); 
            }
        }
    }
    
    public void updateTable(){
        String userName = UserInfo.getFirstName() + ' ' + UserInfo.getLastName();
        RequestJob job = new RequestJob(userName, entityId, 'Apply_metadata');
        String data = JSON.serialize(job);
        HttpService.createRequestTask(data);
    }
    
    public PageReference chackTakenRequest(){
        if(Taken_request__c.getOrgDefaults().request__c){
            PageReference redirect = new PageReference('/apex/Entity_Edit?entityID=' + entityId);
            redirect.setRedirect(true);
            Taken_request__c tr = Taken_request__c.getOrgDefaults();
            tr.request__c = false;
            update tr; 
            return redirect;
        }
        return null;
    }
}