ss/retrieveUnpackaged/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schema_Name__c</fullName>
        <label>Schema Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>127</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ss/retrieveUnpackaged/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_id__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>NVARCHAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLOAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ss/retrieveUnpackaged/classes/EntityController.cls
public class EntityController {

    public List<Entity__c> entities {get; set;}
    public Entity__c entity {get; set;}
    
    public Entity__c createdEntity {get; set;}
    public List<Field__c> createdFields{get; set;}
    public String fieldId {get; set;}
    public Integer fakeId {get; set;}
    
    public Boolean showSection{get;set;}
    public String entityId{get; set;}
    
    public EntityController (){
       entities = [SELECT Name__c, Schema_Name__c, Table_Name__c FROM Entity__c];
       entity = new Entity__c();
       createdEntity = new Entity__c();
       createdFields = new List<Field__c>();
       showSection = false;
       fakeId = 1; 
    }
    
    public void deleteEntity(){
        Entity__c deleteEntity = [SELECT Id, Name__c, Schema_Name__c, Table_Name__c FROM Entity__c WHERE Id =: entityId];
        for(Integer i = 0; i < entities.size(); i++){
            if(entities.get(i).Id == deleteEntity.Id){
              entities.remove(i); 
            }
        }
        delete deleteEntity;
    }
    
    public PageReference  getEntityEditPage(){
        PageReference redirect = new PageReference('/apex/Entity_Edit');
        redirect.getParameters().put('entityID', entityId);
        return redirect;
    }
    
    public void show() {
         if(showSection){
             showSection = false;
         }else{
             showSection = true;
         }      
    }
    
    public void saveEntity(){
    try{
           insert createdEntity;
           entities.add(createdEntity); 
               for(Integer i = 0; i < createdFields.size(); i++){
                    createdFields.get(i).id__c = (entityId + createdFields.get(i).Column_Name__c).toUpperCase();
                    createdFields.get(i).Entity_id__c = createdEntity.Id;
               }
           insert createdFields;
           createdEntity = new Entity__c();
           createdFields = new List<Field__c>();
       }catch(Exception ex){
         ApexPages.addMessages(ex);  
       } 
    }
    
    public void cancelSavingEntity(){
       createdEntity = new Entity__c();
       createdFields = new List<Field__c>(); 
    }
    
    public void createField(){
        Field__C field = new Field__c(Id__c = String.valueOf(fakeId++), Field_Type__c = 'NVARCHAR');
        createdFields.add(field);
    }
    
    public void deleteField(){
        for(Integer i = 0; i < createdFields.size(); i++){
            if(createdFields.get(i).Id__c == fieldId){
              createdFields.remove(i); 
            }
        }
    }
}