ss/retrieveUnpackaged/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schema_Name__c</fullName>
        <label>Schema Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>127</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Entity_id__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/classes/EntityDto.cls
public class EntityDto {
    public String id;
    public String name;
    public String schemaName;
    public String tableName;
    public List<FieldDto> fieldList;
   
    public EntityDto(Entity__c entity){
        id = entity.Id__c;
        name = entity.Name__c;
        schemaName = entity.Schema_Name__c;
        tableName = entity.Table_Name__c;
        if(!entity.Fields__r.isempty()){
            fieldList = new List<FieldDto>();
            for(Field__c field: entity.Fields__r){
               FieldDto fieldDto = new FieldDto(field);
               fieldList.add(fieldDto); 
            }
        }
    }
    
    public void addFieldList(List<FieldDto> fields){
        fieldList = fields;
    }
}