ss/retrieveUnpackaged/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schema_Name__c</fullName>
        <label>Schema Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>127</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>NVARCHAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLOAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/classes/TestEntityController.cls
@isTest
public class TestEntityController {
    
    @isTest static void testShow(){
        EntityController entityController = new EntityController();
        entityController.show();
        Boolean expected = true;
        Boolean actual = entityController.showSection;
        System.assertEquals(expected, actual);
        entityController.show();
        Boolean expected1 = false;
        Boolean actual1 = entityController.showSection;
        System.assertEquals(expected1, actual1);
    }
    
    @isTest static void testCreateField(){
        EntityController entityController = new EntityController();
        Integer fieldId = 1;
        List<Field__c> expected = new List<Field__c>();
        expected.add(new Field__c(Id__c = String.valueOf(fieldId), Field_Type__c = 'NVARCHAR'));
        entityController.fakeId = fieldId;
        
        Test.startTest();
        entityController.createField();
        Test.stopTest();
        
        List<Field__c> actual = entityController.createdFields;
        System.assertEquals(expected, actual);
    }
    
    @isTest static void testDeleteField(){
        EntityController entityController = new EntityController();
        Integer fieldId = 1;
        List<Field__c> fields = new List<Field__c>();
        fields.add(new Field__c(Id__c = String.valueOf(fieldId)));
        entityController.fieldId = String.valueOf(fieldId);
        entityController.createdFields = fields;
        
        Test.startTest();
        entityController.deleteField();
        Test.stopTest();
        
        List<Field__c> expected = new List<Field__c>();
        List<Field__c> actual =  entityController.createdFields;
        System.assertEquals(expected, actual);
    }
    
    @isTest static void testDeleteEntity(){
        EntityController entityController = new EntityController();
        Entity__c entity = new Entity__c( Name__c = 'Barvinok', Schema_Name__c = 'BARVINOK', Table_Name__c = 'TABLE_BARVINOK' );
        insert entity;
        List<Entity__c> entities = new List<Entity__c>();
        entities.add(entity);
        String entityId = entity.Id;
        entityController.entities = entities;
        entityController.entityId = entityId;
        
        Test.startTest();
        entityController.deleteEntity();
        Test.stopTest();
        
        List<Entity__c> expected = new List<Entity__c>();
        List<Entity__c> actual = entityController.entities;
        System.assertEquals(expected, actual);
    }
    
    @isTest static void testCancelSavingEntity(){
       EntityController entityController = new EntityController();
       Entity__c entity = new Entity__c( Name__c = 'Barvinok', Schema_Name__c = 'BARVINOK', Table_Name__c = 'TABLE_BARVINOK' );
       Field__c field = new Field__c(Name__c = 'date', Column_Name__c = 'Date', Field_Type__c = 'NVARCHAR'); 
       List<Field__c> fields = new List<Field__c>();
       fields.add(field);
       entityController.createdFields = fields;
       entityController.createdEntity = entity;
        
       Test.startTest(); 
       entityController.cancelSavingEntity();
       Test.stopTest();
        
       Entity__c expectedEntity = new Entity__c();
       List<Field__c> expectedFields = new List<Field__c>();
       Entity__c actualEntity = entityController.createdEntity;
       List<Field__c> actualFields = entityController.createdFields;
       System.assertEquals(expectedEntity, actualEntity);
       System.assertEquals(expectedFields, actualFields);
    }
     
    @isTest static void testGetEntityEditPage(){
       EntityController entityController = new EntityController();
       String entityId = '2';
       entityController.entityId = entityId; 
       PageReference redirectEx = new PageReference('/apex/Entity_Edit');
       redirectEx.getParameters().put('entityID', entityId);
        
       Test.startTest();
       PageReference redirectAc = entityController.getEntityEditPage();
       Test.stopTest();
        
       String expected = redirectEx.getUrl();
       String actual =  redirectAc.getUrl();   
       System.assertEquals(expected, actual);
    }
    
    @isTest static void testSaveEntity(){
        EntityController entityController = new EntityController();
        Entity__c createdEntity = new Entity__c( Name__c = 'Barvinok', Schema_Name__c = 'BARVINOK', Table_Name__c = 'TABLE_BARVINOK' );
        List<Field__c> createdFields = new List<field__c>();
        Field__c field = new Field__c(Name__c = 'testDate', Column_Name__c = 'TESTDATE', Field_Type__c = 'NVARCHAR', Length__c = 45);
        createdFields.add(field);
        String entityId = createdEntity.Id__c;
        entityController.entityId = entityId;
        entityController.createdEntity = createdEntity;
        entityController.createdFields = createdFields;
        
        Test.startTest();
        entityController.saveEntity();
        Test.stopTest();
        
        Entity__c expectedEntity = new Entity__c();
        Entity__c actualEntity = entityController.createdEntity;
        System.assertEquals(expectedEntity, actualEntity);
        List<Field__c> expectedFields = new List<Field__c>();
        List<Field__c> actualFields = entityController.createdFields;
        System.assertEquals(expectedFields, actualFields);
    }
    
    @isTest static void testSaveEntityGetException(){
       EntityController entityController = new EntityController();
       Entity__c createdEntity = new Entity__c( Name__c = 'Barvinok', Schema_Name__c = 'BARVINOK', Table_Name__c = 'TABLE_BARVINOK' );
        insert createdEntity;
        entityController.createdEntity = createdEntity;
        
        Test.startTest();
        entityController.saveEntity();
        Test.stopTest();
        
        String expected = 'cannot specify Id in an insert call';
        String actual = ApexPages.getMessages().get(0).getDetail();
        System.assertEquals(expected, actual);
    }
}