ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>NVARCHAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLOAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/classes/FieldDto.cls
public class FieldDto {
    String id;
	String name;
    String ColumnName;
    String type;
    Integer length = 0;
    
    public FieldDto(Field__c field){
        id = field.Id__c;
        name = field.Name__c;
        ColumnName = field.Column_Name__c;
        type = field.Field_Type__c;
        if(!String.isEmpty(String.valueOf(field.Length__c))){
        	length = field.Length__c.intValue(); 
        }
    }
}