ui/src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>NVARCHAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLOAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isUnique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isUnique</label>
        <type>Checkbox</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ui/src/classes/Field.cls
public class Field {
    public String id{get; set;}
	public String name{get; set;}
    public String ColumnName{get; set;}
    public String type{get; set;}
    public Integer length{get; set;}
    public Boolean unique{get; set;}
    
    public Field(Field__c field){
        name = field.Name__c;
        ColumnName = field.Column_Name__c;
        type = field.Field_Type__c;
        unique = field.isUnique__c;
        if(!String.isEmpty(String.valueOf(field.Length__c)) && field.Field_Type__c == 'NVARCHAR'){
        	length = field.Length__c.intValue(); 
        }else{
            length = 0;
        }
    }
    
    public Field__c convertIntoSField(){
        Field__c field = new Field__c();
        field.Id__c = this.id;
        field.Name__c = this.name;
        field.Column_Name__c = this.ColumnName;
        field.Field_Type__c = this.type;
        field.isUnique__c = this.unique;
        if(this.length > 0){
           field.Length__c = this.length;    
        }else{
           field.Length__c = null; 
        }

        return field;
    }
    public Field(){
        
    }
}